# Build stage
FROM node:22-alpine AS build
WORKDIR /usr/src/app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
COPY ui/package.json ui/pnpm-lock.yaml ./ui/
WORKDIR /usr/src/app/ui
RUN pnpm install --prod=false

COPY ui ./
RUN pnpm build

# Runtime stage
FROM nginx:alpine

COPY --from=build /usr/src/app/ui/dist /app
COPY --from=build /usr/src/app/ui/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
