name: Build Lawndon

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build-lawndon:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino cli
        uses: arduino/setup-arduino-cli@v2

      - name: Install libraries
        run: |
          arduino-cli lib install IBusBM Servo

      - name: Compile Lawndon
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:mega"
          libraries: |
            - name: IBusBM
            - name: Servo
          sketch-paths: |
            - ./lawndon
          enable-warnings-report: true
          verbose: false
          cli-compile-flags: |
            - --export-binaries

      - name: Package build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          for dir in ./lawndon/build/*; do
            if [ -d "${dir}" ]; then
              tar -czvf "${dir}.tar.gz" -C "${dir}" .
            fi
          done

      - name: Release build
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lawndon/build/*.tar.gz

  build-lawndon-pi:
    runs-on: ubuntu-latest
    needs: build-lawndon
    env:
      WORKING_DIR: ./pi
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement security.insecure
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./pi
          file: ./pi/Dockerfile.server
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/lawndon-pi-server:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/lawndon-pi-server:${{ github.sha }}

      - name: Build and push UI image
        uses: docker/build-push-action@v4
        with:
          context: ./pi
          file: ./pi/Dockerfile.ui
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/lawndon-pi-ui:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/lawndon-pi-ui:${{ github.sha }}
