name: Compile Lawndon Lite

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino cli
        uses: arduino/setup-arduino-cli@v1

      - name: Install libraries
        run: |
          arduino-cli lib install IBusBM
          arduino-cli lib install Servo
      
      - name: Compile Lawndon
        uses: arduino/compile-sketches@v1
        with: 
          fqbn: "arduino:avr:mega"
          libraries: | 
            - name: IBusBM
            - name: Servo
          sketch-paths: |
            - ./lawndon
          enable-warnings-report: true
          verbose: false
          cli-compile-flags: |
            - --export-binaries

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lawndon/build/arduino.avr.mega/*
